version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules

  server:
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    build: ./server
    depends_on:
      - db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
